# Generated by Django 4.0.6 on 2022-08-14 12:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(help_text='It is a phone number.', max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone number')),
                ('email', models.EmailField(help_text='It is an email.', max_length=254, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='Email')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='It is a tag.', max_length=16, unique=True, verbose_name='Tag name')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='It is a contact name.', max_length=200, verbose_name='Contact name')),
                ('birthday', models.DateField(blank=True, default=django.db.models.deletion.SET_NULL, help_text='It is a contact birthday', verbose_name='Contact birthday')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('contact_details_by_foreign_key', models.ForeignKey(blank=True, default=django.db.models.deletion.SET_NULL, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_related_by_foreign_key', to='contacts.contactdetail')),
                ('tag_many_to_many', models.ManyToManyField(related_name='contact_related_by_many_to_many', to='contacts.tag')),
            ],
        ),
    ]
