# Generated by Django 4.0.6 on 2022-08-15 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='tag_many_to_many',
            field=models.ManyToManyField(blank=True, related_name='contact_related_by_many_to_many', to='contacts.tag'),
        ),
    ]
