# Generated by Django 4.0.6 on 2022-08-14 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_alter_contact_contact_details_by_foreign_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='birthday',
            field=models.DateField(blank=True, default=None, help_text='It is a contact birthday', verbose_name='Contact birthday'),
        ),
    ]
