# Generated by Django 4.0.6 on 2022-08-08 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('humans', '0002_human_favourite_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the color.', max_length=32, verbose_name='Name')),
            ],
        ),
        migrations.AddField(
            model_name='human',
            name='favourite_color_by_foreigh_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='humans.color'),
        ),
    ]
