# Generated by Django 4.0.6 on 2022-08-08 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('humans', '0003_color_human_favourite_color_by_foreigh_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='human',
            old_name='favourite_color_by_foreigh_key',
            new_name='favourite_color_by_foreign_key',
        ),
    ]
