# Generated by Django 4.0.6 on 2022-08-09 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('humans', '0004_rename_favourite_color_by_foreigh_key_human_favourite_color_by_foreign_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='human',
            name='favourite_color_many_to_many',
            field=models.ManyToManyField(related_name='human_related_by_many_to_many', to='humans.color'),
        ),
        migrations.AlterField(
            model_name='human',
            name='favourite_color_by_foreign_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='humans_related_by_foreign_key', to='humans.color'),
        ),
    ]
